  base = "/"
  publish = "dist"
  command = "npm install"

  [context.branch-deploy.environment]
  NODE_ENV = "development"

  [context.production]
  environment = {  NODE_ENV = "development"}

  [build.environment]
  NODE_ENV = "development"
